### ISSUE TITLE
collab with the bot detector plugin?

### ISSUE THREAD

**Issue by extreme4all** [lukearend/osrs-hiscores#1]
Hey there, one of the maintainers of the bot detector plugin.
we pretty much do the same / similar thing for our bot detection, want to collab/ contribute?

https://github.com/Bot-detector
https://discord.gg/38yN3nqMqE

**Comment by lukearend** [comment]
Hey there, nice to hear from you. I would be interested in collaborating in the future. I've set this project down for the time being (it's frozen in a nice state), but next time I come back to this area, I'd be happy to work on it alongside you guys.

Thanks for the links.
