### ISSUE TITLE
the page endpoint is not intended for scraping

### ISSUE THREAD

**Issue by extreme4all** [lukearend/osrs-hiscores#2]
https://github.com/lukearend/osrs-hiscores/blob/e9bbcf51b7b3132145c281a40d1e7badf06ef2a4/src/scrape/requests.py#L34

in the past this endpoint was strictly protected by imperva, it seems to be less protected now, but extensive scraping of unintended pages might cause issues.

**Comment by lukearend** [comment]
Gotcha. I'll get in touch with you and the other bot detection people about data collection in the future. Is there currently an intended API for this kind of scraping?

**Comment by extreme4all** [comment]
i believe:
`https://secure.runescape.com/m=hiscore_oldschool/index_lite.ws?player={player['name']}`

The runescape documentation on it
https://runescape.wiki/w/Application_programming_interface#Hiscores_Lite_2
